In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
hyperparameter_results=pd.read_csv('hyperparameter_tuning.csv')
hyperparameter_results.head()

,max_depth_c,n_est_c,max_depth_r,n_est_r,test_acc_1,test_acc_2,test_acc_3,test_f1_1,test_f1_2,test_f1_3,test_r2_1,test_r2_2,test_r2_3,overall_r2_1,overall_r2_2,overall_r2_3
0,15.0,100,15.0,100,0.809673,0.808628,0.806538,0.879992,0.878850,0.877462,0.043850,0.350668,0.305207,0.043300,0.305781,0.329503
1,15.0,100,15.0,150,0.810008,0.811262,0.809088,0.880171,0.880407,0.879151,0.023568,0.325324,0.319281,0.025445,0.299591,0.358638
2,15.0,100,15.0,200,0.808753,0.810008,0.807458,0.879316,0.879593,0.878051,0.059234,0.342829,0.320799,0.061361,0.364042,0.342987
3,15.0,100,30.0,100,0.808586,0.809130,0.806622,0.879389,0.878963,0.877664,0.151966,0.353347,0.337773,0.137760,0.320426,0.359681
4,15.0,100,30.0,150,0.809046,0.809506,0.807165,0.879682,0.879121,0.877947,0.123989,0.366025,0.329426,0.122700,0.302478,0.352633

In [15]:
regression_frame=hyperparameter_results[['max_depth_r','n_est_r','max_depth_c','n_est_c','overall_r2_2','overall_r2_3']]
regression_frame.head()

   max_depth_r  n_est_r  max_depth_c  n_est_c  overall_r2_2  overall_r2_3
0         15.0      100         15.0      100      0.305781      0.329503
1         15.0      150         15.0      100      0.299591      0.358638
2         15.0      200         15.0      100      0.364042      0.342987
3         30.0      100         15.0      100      0.320426      0.359681
4         30.0      150         15.0      100      0.302478      0.352633

In [19]:
regression_frame['avg_r2']=pd.to_numeric((regression_frame['overall_r2_2']+regression_frame['overall_r2_3'])/2)
regression_frame.head()

C:\Users\noahw\Anaconda3\envs\ipykernel_py3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

,max_depth_r,n_est_r,max_depth_c,n_est_c,overall_r2_2,overall_r2_3,avg_r2
0,15,100,15,100,0.305781,0.329503,0.317642
1,15,150,15,100,0.299591,0.358638,0.329115
2,15,200,15,100,0.364042,0.342987,0.353514
3,30,100,15,100,0.320426,0.359681,0.340053
4,30,150,15,100,0.302478,0.352633,0.327555

In [20]:
regression_frame.replace({np.nan:'No Limit'},inplace=True)

C:\Users\noahw\Anaconda3\envs\ipykernel_py3\lib\site-packages\pandas\core\generic.py:3836: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  limit=limit, regex=regex)

In [21]:
regression_frame.dtypes

max_depth_r      object
n_est_r           int64
max_depth_c      object
n_est_c           int64
overall_r2_2    float64
overall_r2_3    float64
avg_r2          float64
dtype: object

In [12]:
regression_frame.groupby('max_depth_r').agg({'avg_r2':'mean'})

               avg_r2
max_depth_r
15.0         0.326788
30.0         0.336760
No Limit     0.335688

In [13]:
regression_frame.groupby('n_est_r').agg({'avg_r2':'mean'})

           avg_r2
n_est_r
100      0.330673
150      0.333742
200      0.334821

In [22]:
regression_frame.sort_values('avg_r2',ascending=False)

,max_depth_r,n_est_r,max_depth_c,n_est_c,overall_r2_2,overall_r2_3,avg_r2
51,No Limit,100,30,200,0.383072,0.376681,0.379876
30,30,100,30,100,0.389475,0.366393,0.377934
10,15,150,15,150,0.380202,0.372067,0.376135
34,No Limit,150,30,100,0.389452,0.361362,0.375407
66,30,100,No Limit,150,0.374925,0.375735,0.375330
50,30,200,30,200,0.386458,0.360272,0.373365
59,30,200,No Limit,100,0.370721,0.375099,0.372910
79,No Limit,150,No Limit,200,0.382406,0.355157,0.368782
46,15,150,30,200,0.382063,0.354088,0.368075
7,No Limit,150,15,100,0.377420,0.357979,0.367700
57,30,100,No Limit,100,0.371374,0.361185,0.366280
26,No Limit,200,15,200,0.385538,0.345058,0.365298
18,15,100,15,200,0.374515,0.351591,0.363053
55,15,150,No Limit,100,0.372427,0.352240,0.362333
22,30,150,15,200,0.362502,0.360112,0.361307
64,15,150,No Limit,150,0.379598,0.334930,0.357264
80,No Limit,200,No Limit,200,0.327115,0.386350,0.356733
16,No Limit,150,15,150,0.361190,0.347428,0.354309
2,15,200,15,100,0.364042,0.342987,0.353514
41,30,200,30,150,0.319815,0.384939,0.352377
61,No Limit,150,No Limit,100,0.325470,0.378118,0.351794
68,30,200,No Limit,150,0.323344,0.375739,0.349541
21,30,100,15,200,0.309284,0.386017,0.347650
8,No Limit,200,15,100,0.308419,0.383238,0.345829
75,30,100,No Limit,200,0.310033,0.381248,0.345640
62,No Limit,200,No Limit,100,0.315180,0.374800,0.344990
35,No Limit,200,30,100,0.313999,0.375941,0.344970
6,No Limit,100,15,100,0.322337,0.365435,0.343886
43,No Limit,150,30,150,0.305723,0.381538,0.343631
47,15,200,30,200,0.314902,0.370676,0.342789
...,...,...,...,...,...,...,...
31,30,150,30,100,0.314101,0.351189,0.332645
28,15,150,30,100,0.300964,0.363621,0.332292
40,30,150,30,150,0.319905,0.344674,0.332290
58,30,150,No Limit,100,0.309787,0.351025,0.330406
48,30,100,30,200,0.307289,0.353134,0.330211
29,15,200,30,100,0.306959,0.353035,0.329997
17,No Limit,200,15,150,0.307120,0.352434,0.329777
70,No Limit,150,No Limit,150,0.310026,0.349481,0.329753
49,30,150,30,200,0.307099,0.351596,0.329347
1,15,150,15,100,0.299591,0.358638,0.329115
54,15,100,No Limit,100,0.308555,0.347225,0.327890
4,30,150,15,100,0.302478,0.352633,0.327555
72,15,100,No Limit,200,0.308339,0.346718,0.327528
5,30,200,15,100,0.299038,0.355452,0.327245
71,No Limit,200,No Limit,150,0.309959,0.343292,0.326625
38,15,200,30,150,0.293660,0.359141,0.326401
27,15,100,30,100,0.301705,0.350983,0.326344
32,30,200,30,100,0.309406,0.341834,0.325620
67,30,150,No Limit,150,0.304766,0.342234,0.323500
45,15,100,30,200,0.291124,0.352564,0.321844
56,15,200,No Limit,100,0.305863,0.336621,0.321242
76,30,150,No Limit,200,0.305557,0.336782,0.321169
78,No Limit,100,No Limit,200,0.306673,0.335518,0.321095
20,15,200,15,200,0.297013,0.342605,0.319809
0,15,100,15,100,0.305781,0.329503,0.317642
13,30,150,15,150,0.299489,0.334650,0.317070
42,No Limit,100,30,150,0.302554,0.331344,0.316949
63,15,100,No Limit,150,0.288850,0.342483,0.315666
73,15,150,No Limit,200,0.298226,0.331949,0.315088
9,15,100,15,150,0.307960,0.296771,0.302365

# Tuning for Population Size

In [3]:
#read the data
solar=pd.read_csv('../deepsolar_tract.csv',encoding = "ISO-8859-1")
solar_fields=pd.read_csv('../deepsolar fields.csv')

features=solar_fields.loc[(solar_fields['Mentioned in Supplemental Info']==1)]['Field'].tolist()
all_variables=features+['number_of_solar_system_per_household']

In [16]:
solar2=solar[all_variables].loc[(np.isfinite(solar['number_of_solar_system_per_household']))
                                & (solar['population']>1000)]

In [17]:
solar2.shape

(71095, 96)

In [6]:
solar.shape

(72537, 169)

In [18]:
pop_limit=pd.read_csv('pop_limit.csv')
pop_limit

,pop_limit,test_acc_1,test_acc_2,test_acc_3,test_f1_1,test_f1_2,test_f1_3,test_r2_1,test_r2_2,test_r2_3,overall_r2_1,overall_r2_2,overall_r2_3
0,0,0.808837,0.812516,0.809589,0.878225,0.880842,0.877911,0.071280,0.320318,0.098659,0.087312,0.323954,0.117850
1,20,0.807889,0.810064,0.808181,0.876886,0.879193,0.877759,0.397613,0.464912,0.502639,0.414195,0.475642,0.503969
2,50,0.808896,0.814294,0.808512,0.878528,0.881483,0.877608,0.417467,0.525327,0.458899,0.459621,0.519711,0.470600
3,100,0.810271,0.808639,0.810598,0.879194,0.877872,0.879079,0.549108,0.393538,0.515806,0.584678,0.387076,0.523336
4,500,0.809777,0.812537,0.807589,0.878615,0.880445,0.877773,0.437853,0.516082,0.423159,0.431423,0.525699,0.420467
5,1000,0.807924,0.814077,0.810322,0.877838,0.882369,0.879001,0.548836,0.413910,0.555080,0.552340,0.421302,0.563345

In [19]:
pop_limit['avg_r2']=pd.to_numeric((pop_limit['overall_r2_1']+pop_limit['overall_r2_2']+pop_limit['overall_r2_3'])/3)
pop_limit

,pop_limit,test_acc_1,test_acc_2,test_acc_3,test_f1_1,test_f1_2,test_f1_3,test_r2_1,test_r2_2,test_r2_3,overall_r2_1,overall_r2_2,overall_r2_3,avg_r2
0,0,0.808837,0.812516,0.809589,0.878225,0.880842,0.877911,0.071280,0.320318,0.098659,0.087312,0.323954,0.117850,0.176372
1,20,0.807889,0.810064,0.808181,0.876886,0.879193,0.877759,0.397613,0.464912,0.502639,0.414195,0.475642,0.503969,0.464602
2,50,0.808896,0.814294,0.808512,0.878528,0.881483,0.877608,0.417467,0.525327,0.458899,0.459621,0.519711,0.470600,0.483311
3,100,0.810271,0.808639,0.810598,0.879194,0.877872,0.879079,0.549108,0.393538,0.515806,0.584678,0.387076,0.523336,0.498363
4,500,0.809777,0.812537,0.807589,0.878615,0.880445,0.877773,0.437853,0.516082,0.423159,0.431423,0.525699,0.420467,0.459196
5,1000,0.807924,0.814077,0.810322,0.877838,0.882369,0.879001,0.548836,0.413910,0.555080,0.552340,0.421302,0.563345,0.512329